apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-deployment
  labels:
    app: note
spec:
  replicas: 1
  selector:
    matchLabels:
      app: note
  template:
    metadata:
      labels:
        app: note
    spec:
      containers:
        - name: note-service
          image: note-service-image:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 30010
          env:
            - name: ENV
              value: "local"
            - name: ENTRY_POINT
              value: "k8s"
            - name: PORT
              value: "30010"
            - name: DB_PATH
              valueFrom:
                configMapKeyRef:
                  name: k8s-config
                  key: mongo-url
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: k8s-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: k8s-secret
                  key: DB_PASSWORD
            - name: EVENT_BUS_ROUTE
              valueFrom:
                configMapKeyRef:
                  name: k8s-config
                  key: event-bus-url
            - name: EVENT_BUS_PORT
              value: "30000"
---
apiVersion: v1
kind: Service
metadata:
  name: note-service
spec:
  type: NodePort
  selector:
    app: note 
  ports:
    - protocol: TCP
      port: 30010
      targetPort: 30010
      nodePort: 30010
